export const studentSeedData = [
    { "studentId": '1', "name": "Alice Thompson", "email": "alice.thompson@example.com" },
    { "studentId": '2', "name": "Brian Miller", "email": "brian.miller@example.com" },
    { "studentId": '3', "name": "Catherine Zhao", "email": "catherine.zhao@example.com" },
    { "studentId": '4', "name": "David O'Connor", "email": "david.oconnor@example.com" },
    { "studentId": '5', "name": "Elena Rodriguez", "email": "elena.rodriguez@example.com" },
    { "studentId": '6', "name": "Faisal Khan", "email": "faisal.khan@example.com" },
    { "studentId": '7', "name": "Grace Hopper", "email": "grace.hopper@example.com" },
    { "studentId": '8', "name": "Henry Tanaka", "email": "henry.tanaka@example.com" },
    { "studentId": '9', "name": "Isabella Rossi", "email": "isabella.rossi@example.com" },
    { "studentId": '10', "name": "Julian Smith", "email": "julian.smith@example.com" },
    { "studentId": '11', "name": "Kevin Peterson", "email": "kevin.peterson@example.com" },
    { "studentId": '12', "name": "Liam Nguyen", "email": "liam.nguyen@example.com" },
    { "studentId": '13', "name": "Mia Williams", "email": "mia.williams@example.com" },
    { "studentId": '14', "name": "Noah Garcia", "email": "noah.garcia@example.com" },
    { "studentId": '15', "name": "Olivia Brown", "email": "olivia.brown@example.com" },
    { "studentId": '16', "name": "Parker Davis", "email": "parker.davis@example.com" },
    { "studentId": '17', "name": "Quinn Martinez", "email": "quinn.martinez@example.com" },
    { "studentId": '18', "name": "Riley Wilson", "email": "riley.wilson@example.com" },
    { "studentId": '19', "name": "Sophia Anderson", "email": "sophia.anderson@example.com" },
    { "studentId": '20', "name": "Thomas Taylor", "email": "thomas.taylor@example.com" },
    { "studentId": '21', "name": "Ursula Moore", "email": "ursula.moore@example.com" },
    { "studentId": '22', "name": "Victor Jackson", "email": "victor.jackson@example.com" },
    { "studentId": '23', "name": "Wendy White", "email": "wendy.white@example.com" },
    { "studentId": '24', "name": "Xavier Harris", "email": "xavier.harris@example.com" },
    { "studentId": '25', "name": "Yara Clark", "email": "yara.clark@example.com" },
    { "studentId": '26', "name": "Zane Lewis", "email": "zane.lewis@example.com" },
    { "studentId": '27', "name": "Amelia Young", "email": "amelia.young@example.com" },
    { "studentId": '28', "name": "Bennett Hall", "email": "bennett.hall@example.com" },
    { "studentId": '29', "name": "Chloe Allen", "email": "chloe.allen@example.com" },
    { "studentId": '30', "name": "Daniel Wright", "email": "daniel.wright@example.com" },
    { "studentId": '31', "name": "Emily Scott", "email": "emily.scott@example.com" },
    { "studentId": '32', "name": "Franklin Green", "email": "franklin.green@example.com" },
    { "studentId": '33', "name": "Georgia Baker", "email": "georgia.baker@example.com" },
    { "studentId": '34', "name": "Harrison Adams", "email": "harrison.adams@example.com" },
    { "studentId": '35', "name": "Ivy Nelson", "email": "ivy.nelson@example.com" },
    { "studentId": '36', "name": "Jack Carter", "email": "jack.carter@example.com" },
    { "studentId": '37', "name": "Kaitlyn Mitchell", "email": "kaitlyn.mitchell@example.com" },
    { "studentId": '38', "name": "Lucas Perez", "email": "lucas.perez@example.com" },
    { "studentId": '39', "name": "Maya Roberts", "email": "maya.roberts@example.com" },
    { "studentId": '40', "name": "Nathan Turner", "email": "nathan.turner@example.com" },
    { "studentId": '41', "name": "Oscar Phillips", "email": "oscar.phillips@example.com" },
    { "studentId": '42', "name": "Penelope Campbell", "email": "penelope.campbell@example.com" },
    { "studentId": '43', "name": "Quentin Parker", "email": "quentin.parker@example.com" },
    { "studentId": '44', "name": "Ruby Evans", "email": "ruby.evans@example.com" },
    { "studentId": '45', "name": "Sebastian Edwards", "email": "sebastian.edwards@example.com" },
    { "studentId": '46', "name": "Tessa Collins", "email": "tessa.collins@example.com" },
    { "studentId": '47', "name": "Umar Stewart", "email": "umar.stewart@example.com" },
    { "studentId": '48', "name": "Violet Morris", "email": "violet.morris@example.com" },
    { "studentId": '49', "name": "Wyatt Rogers", "email": "wyatt.rogers@example.com" },
    { "studentId": '50', "name": "Zoe Murphy", "email": "zoe.murphy@example.com" }
];

export const configurationSeedData = [
    {
        key: 'student_max_classes_per_day',
        value: 3,
        dataType: 'number',
        description: 'Maximum number of classes a student can schedule per day',
        category: 'limits'
    },
    {
        key: 'instructor_max_classes_per_day',
        value: 5,
        dataType: 'number',
        description: 'Maximum number of classes an instructor can teach per day',
        category: 'limits'
    },
    {
        key: 'class_duration_minutes',
        value: 60,
        dataType: 'number',
        description: 'Default duration of a class in minutes',
        category: 'system'
    },
    {
        key: 'max_classes_per_type_per_day',
        value: 10,
        dataType: 'number',
        description: 'Maximum number of classes of a specific type that can be scheduled per day',
        category: 'limits'
    },
    {
        key: 'enable_student_auto_add',
        value: true,
        dataType: 'boolean',
        description: 'Automatically add new student IDs found in CSV uploads',
        category: 'features'
    },
    {
        key: 'enable_instructor_auto_add',
        value: true,
        dataType: 'boolean',
        description: 'Automatically add new instructor IDs found in CSV uploads',
        category: 'features'
    },
    {
        key: 'enable_class_type_auto_add',
        value: true,
        dataType: 'boolean',
        description: 'Automatically add new class type IDs found in CSV uploads',
        category: 'features'
    }
];
export const instructorSeedData = [
    { "instructorId": "1", "name": "Dr. Aris Thorne", "email": "a.thorne@university.edu" },
    { "instructorId": "2", "name": "Prof. Beatrice Vance", "email": "b.vance@university.edu" },
    { "instructorId": "3", "name": "Dr. Cedric Moore", "email": "c.moore@university.edu" },
    { "instructorId": "4", "name": "Prof. Diana Prince", "email": "d.prince@university.edu" },
    { "instructorId": "5", "name": "Dr. Elias Sterling", "email": "e.sterling@university.edu" },
    { "instructorId": "6", "name": "Prof. Fiona Gallagher", "email": "f.gallagher@university.edu" },
    { "instructorId": "7", "name": "Dr. Gregory House", "email": "g.house@university.edu" },
    { "instructorId": "8", "name": "Prof. Helena Troy", "email": "h.troy@university.edu" },
    { "instructorId": "9", "name": "Dr. Isaac Newton", "email": "i.newton@university.edu" },
    { "instructorId": "10", "name": "Prof. Jacqueline Frost", "email": "j.frost@university.edu" },
    { "instructorId": "11", "name": "Dr. Kieran Lee", "email": "k.lee@university.edu" },
    { "instructorId": "12", "name": "Prof. Laura Palmer", "email": "l.palmer@university.edu" },
    { "instructorId": "13", "name": "Dr. Marcus Aurelius", "email": "m.aurelius@university.edu" },
    { "instructorId": "14", "name": "Prof. Nadia Comaneci", "email": "n.comaneci@university.edu" },
    { "instructorId": "15", "name": "Dr. Oliver Twist", "email": "o.twist@university.edu" },
    { "instructorId": "16", "name": "Prof. Penelope Cruz", "email": "p.cruz@university.edu" },
    { "instructorId": "17", "name": "Dr. Quentin Tarantino", "email": "q.tarantino@university.edu" },
    { "instructorId": "18", "name": "Prof. Regina Phalange", "email": "r.phalange@university.edu" },
    { "instructorId": "19", "name": "Dr. Silas Marner", "email": "s.marner@university.edu" },
    { "instructorId": "20", "name": "Prof. Tabitha Wright", "email": "t.wright@university.edu" },
    { "instructorId": "21", "name": "Dr. Ulysses Grant", "email": "u.grant@university.edu" },
    { "instructorId": "22", "name": "Prof. Victor Von Doom", "email": "v.vondoom@university.edu" },
    { "instructorId": "23", "name": "Dr. Wallace Shawn", "email": "w.shawn@university.edu" },
    { "instructorId": "24", "name": "Prof. Xena Warrior", "email": "x.warrior@university.edu" },
    { "instructorId": "25", "name": "Dr. Yorick Brown", "email": "y.brown@university.edu" },
    { "instructorId": "26", "name": "Prof. Zelda Fitzgerald", "email": "z.fitzgerald@university.edu" },
    { "instructorId": "27", "name": "Dr. Alistair Cook", "email": "a.cook@university.edu" },
    { "instructorId": "28", "name": "Prof. Bernard Lowe", "email": "b.lowe@university.edu" },
    { "instructorId": "29", "name": "Dr. Clara Oswald", "email": "c.oswald@university.edu" },
    { "instructorId": "30", "name": "Prof. Desmond Miles", "email": "d.miles@university.edu" },
    { "instructorId": "31", "name": "Dr. Eleanor Shellstrop", "email": "e.shellstrop@university.edu" },
    { "instructorId": "32", "name": "Prof. Ford Prefect", "email": "f.prefect@university.edu" },
    { "instructorId": "33", "name": "Dr. Gideon Graves", "email": "g.graves@university.edu" },
    { "instructorId": "34", "name": "Prof. Holden Caulfield", "email": "h.caulfield@university.edu" },
    { "instructorId": "35", "name": "Dr. Iris West", "email": "i.west@university.edu" },
    { "instructorId": "36", "name": "Prof. Jonathan Joestar", "email": "j.joestar@university.edu" },
    { "instructorId": "37", "name": "Dr. Kara Danvers", "email": "k.danvers@university.edu" },
    { "instructorId": "38", "name": "Prof. Lucius Fox", "email": "l.fox@university.edu" },
    { "instructorId": "39", "name": "Dr. Minerva McGonagall", "email": "m.mcgonagall@university.edu" },
    { "instructorId": "40", "name": "Prof. Norman Osborn", "email": "n.osborn@university.edu" },
    { "instructorId": "41", "name": "Dr. Oswald Cobblepot", "email": "o.cobblepot@university.edu" },
    { "instructorId": "42", "name": "Prof. Pamela Isley", "email": "p.isley@university.edu" },
    { "instructorId": "43", "name": "Dr. Quintus Lentulus", "email": "q.lentulus@university.edu" },
    { "instructorId": "44", "name": "Prof. River Song", "email": "r.song@university.edu" },
    { "instructorId": "45", "name": "Dr.塞缪尔 Oak", "email": "s.oak@university.edu" },
    { "instructorId": "46", "name": "Prof.泰瑞斯 Miller", "email": "t.miller@university.edu" },
    { "instructorId": "47", "name": "Dr. Uriel Septim", "email": "u.septim@university.edu" },
    { "instructorId": "48", "name": "Prof. Vivien Leigh", "email": "v.leigh@university.edu" },
    { "instructorId": "49", "name": "Dr. Winston Smith", "email": "w.smith@university.edu" },
    { "instructorId": "50", "name": "Prof. Zaphod Beeblebrox", "email": "z.beeblebrox@university.edu" }
];

export const classTypeSeedData = [
    { "classTypeId": 1, "name": "Introduction to Psychology", "description": "Exploration of the human mind and behavior patterns." },
    { "classTypeId": 2, "name": "Calculus I", "description": "Fundamental concepts of limits, derivatives, and integrals." },
    { "classTypeId": 3, "name": "Organic Chemistry", "description": "Study of carbon-based compounds and their reactions." },
    { "classTypeId": 4, "name": "Ancient World History", "description": "Survey of civilizations from Mesopotamia to the fall of Rome." },
    { "classTypeId": 5, "name": "Macroeconomics", "description": "Analysis of national income, inflation, and economic growth." },
    { "classTypeId": 6, "name": "Modern Art History", "description": "Examining art movements from Impressionism to the present." },
    { "classTypeId": 7, "name": "Data Structures", "description": "Organization and management of data for efficient access." },
    { "classTypeId": 8, "name": "Environmental Science", "description": "Interdisciplinary study of human impact on the ecosystem." },
    { "classTypeId": 9, "name": "Business Ethics", "description": "Examining moral dilemmas in the modern corporate world." },
    { "classTypeId": 10, "name": "Microbiology", "description": "Study of microscopic organisms and their roles in disease." },
    { "classTypeId": 11, "name": "Creative Writing", "description": "Workshop-based course focusing on fiction and poetry." },
    { "classTypeId": 12, "name": "Criminal Justice", "description": "Overview of the legal system, policing, and corrections." },
    { "classTypeId": 13, "name": "Digital Marketing", "description": "Strategies for SEO, social media, and online advertising." },
    { "classTypeId": 14, "name": "Astrophysics", "description": "Physics of celestial bodies and the universe's evolution." },
    { "classTypeId": 15, "name": "Ethics in AI", "description": "Discussion on the societal and moral impact of automation." },
    { "classTypeId": 16, "name": "Public Speaking", "description": "Techniques for effective oral communication and presentation." },
    { "classTypeId": 17, "name": "Genetics", "description": "Principles of heredity and variation in living organisms." },
    { "classTypeId": 18, "name": "Web Development", "description": "Building modern applications using HTML, CSS, and JS." },
    { "classTypeId": 19, "name": "Sociology", "description": "Scientific study of society and social interaction." },
    { "classTypeId": 20, "name": "Abnormal Psychology", "description": "Study of mental disorders and clinical treatments." },
    { "classTypeId": 21, "name": "Linear Algebra", "description": "Vectors, matrices, and systems of linear equations." },
    { "classTypeId": 22, "name": "Marine Biology", "description": "Study of organisms in the ocean and other brackish bodies." },
    { "classTypeId": 23, "name": "Political Science", "description": "Theory and practice of politics and government systems." },
    { "classTypeId": 24, "name": "Human Anatomy", "description": "Detailed study of the structure of the human body." },
    { "classTypeId": 25, "name": "Software Engineering", "description": "Systematic approach to software development and design." },
    { "classTypeId": 26, "name": "Philosophy 101", "description": "Inquiry into the nature of knowledge, reality, and existence." },
    { "classTypeId": 27, "name": "Global Logistics", "description": "Management of the flow of goods across international borders." },
    { "classTypeId": 28, "name": "Thermodynamics", "description": "Study of heat, work, and energy transformations." },
    { "classTypeId": 29, "name": "Anthropology", "description": "The study of human societies and cultural development." },
    { "classTypeId": 30, "name": "Graphic Design", "description": "Visual communication using typography, photography, and icons." },
    { "classTypeId": 31, "name": "Neuroscience", "description": "Structure and function of the nervous system and brain." },
    { "classTypeId": 32, "name": "Game Design", "description": "Principles of mechanics, narrative, and player psychology." },
    { "classTypeId": 33, "name": "Italian Renaissance", "description": "Cultural and artistic achievements in 15th-century Italy." },
    { "classTypeId": 34, "name": "Cybersecurity", "description": "Protecting systems and networks from digital attacks." },
    { "classTypeId": 35, "name": "Journalism", "description": "Reporting, writing, and editing for news media outlets." },
    { "classTypeId": 36, "name": "Statistical Analysis", "description": "Collection and interpretation of complex data sets." },
    { "classTypeId": 37, "name": "Nutrition Science", "description": "Relationship between food and human health/disease." },
    { "classTypeId": 38, "name": "Cloud Computing", "description": "Architectural principles of remote server networks." },
    { "classTypeId": 39, "name": "International Law", "description": "Rules governing relationships between sovereign states." },
    { "classTypeId": 40, "name": "Forensic Science", "description": "Application of science to criminal and civil laws." },
    { "classTypeId": 41, "name": "Renewable Energy", "description": "Exploring solar, wind, and hydroelectric power sources." },
    { "classTypeId": 42, "name": "Social Media Trends", "description": "Analyzing viral content and platform algorithms." },
    { "classTypeId": 43, "name": "Classical Literature", "description": "Study of great works from Greek and Roman antiquity." },
    { "classTypeId": 44, "name": "Robotics", "description": "Design, construction, and operation of autonomous robots." },
    { "classTypeId": 45, "name": "Film Production", "description": "Hands-on guide to cinematography, lighting, and sound." },
    { "classTypeId": 46, "name": "Behavioral Economics", "description": "Psychological insights into economic decision-making." },
    { "classTypeId": 47, "name": "Quantum Mechanics", "description": "Physical properties of nature at the scale of atoms." },
    { "classTypeId": 48, "name": "Linguistics", "description": "Scientific study of language structure and evolution." },
    { "classTypeId": 49, "name": "Landscape Architecture", "description": "Designing outdoor public areas and landmarks." },
    { "classTypeId": 50, "name": "User Experience (UX)", "description": "Focusing on usability and accessibility of digital products." }
]